### PR TITLE
Webpack GitHub deployments

### PR DESCRIPTION
**Pull request by dennari**
Deployment and notifications related improvements from master. Also some housekeeping and bugfixes.

### CODE REVIEW

**Comment by juhoojala** [comment]
Does this implementation allow for overriding some of the `deployOptions` by providing them via `opts` to `prepareBuildTasks`?

**Comment by juhoojala** [comment]
Maybe I'm missing something, but I'm talking about overriding `deployOptions`, and I don't see a way to do that. 

For example I would like to have the ability to pass some `opts.deployOptions` to define that builds with `LUCIFY_ENV` set to `development` should go to a different bucket than `lucify-dev`.

**Comment by dennari** [comment]
Yes you were right that three properties defined in the `deployOptions` were not overridable. I fixed that and added a test for it as well.

**Comment by juhoojala** [comment]
Looking quickly, this only allows for making a fixed override to `deployOptions`. It does not allow for specifying that with a given `LUCIFY_ENV` we should use a given bucket, etc. For example we might wish to have a project that uses a different bucket when deploying to `production`, and for other environments use the default buckets in `deploy-options`.

This was fairly simply implemented with `object-extend` in the master branch.

**Comment by dennari** [comment]
Yes, you're right that they're fixed once passed forward from the topmost level. You can of course always include env dependent logic on the topmost level. I think this is somewhat more explicit than the `object-extend` approach, although I don't see a big difference.

**Comment by dennari** [comment]
So the _big_ feature implemented in this PR is that `lucify-component-builder` now communicates with Flowdock by creating deployments with the Github deployments api (GHDAPI) instead of using the Flowdock api directly. There are a couple of advantages:
1. _All_ the deployments, including the ones that are not created through Lucifer, are accessible through GHDAPI.
2. There is only a single pathway for communicating about deployments to Flowdock and that is:
   1. Create a deployment to the GHDAPI with sufficient metadata in the payload ([see here](src/js/prepare-build-tasks.js#L210-L234))
   2. GHDAPI fires a webhook to Heaven about the deployment
   3. Heaven tracks the deployment process and creates `deployment_status` messages to GHDAPI
   4. Also the `deployment_status` messages cause the webhook to fire back to Heaven
   5. Every `deployment_status` message received by Heaven makes it push information to Flowdock
3. Heaven's Flowdock integration is much more advanced than what we had implemented through the deprecated Flowdock push API.

_Q:_ Normally Heaven uses the CircleCI API to launch a new build. How do you make sure that doesn't happen when the build is already running?

_A:_ When the deployment to GHDAPI is created _after_ the build in CircleCI has already been started, we include a parameter in the GHDAPI deployment payload identifying the CircleCI build ([see here](https://github.com/lucified/lucify-component-builder/blob/webpack-github-deployments/src/js/prepare-build-tasks.js#L231)). This causes Heaven's CircleCI provider to only follow the progress and skips creating a new build.

_Q:_ How do you pass the website url to Heaven? It's only known after the build has been completed, i.e. it cannot be included in the GHDAPI deployment payload.

_A:_ This is done with CircleCI's support for _build artifacts_. After the build has completed Heaven's CirceCI provider checks for the existence of a build artifact containing the url and if found passes it to Flowdock.

**Comment by dennari** [comment]
When the build is initiated by Lucifer from a Flowdock flow, the deployment information is posted to the same flow. When there is no initial flow, how do we decide where to post the deployment information? This can be controlled by providing a flow _id_ to lucify-component-builder: https://github.com/lucified/lucify-component-builder/blob/webpack-github-deployments/src/js/deploy-options.js#L94-L102. A tricky thing is, where do you get these ids? I've only seen them as part of the API responses.

**Comment by juhoojala** [comment]
Since the flow id is not a secret, it is probably most straight-forward to put into `opts` in `gulpfile.js`

**Comment by juhoojala** [comment]
Closing as these has been merged outside this PR

**Pull request closed without merging**
